/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.unipar.poo.AARE2.Screen;


import javax.swing.JOptionPane;
import br.com.unipar.poo.AARE2.Controller.*;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Matheus
 */
public class OrderScreen extends javax.swing.JFrame {
    double Border,NoBorder, BorderPrice1, BorderPrice2, Price, PriceBorder, PriceFlavor = 0.0;
    double pricecoke, priceheineken, pricepratz, pricewater;
    int Flavors, QtFlavors = 0, CountFlavors = 0, w =0, p = 0, h = 0, c = 0;
    String Size;
    Pizza Pizza1 = new Pizza();
    ArrayList<String> flavor = new ArrayList();
    JFrame Frame;
    
    /**
     * 
     * Creates new form OrderScreen
     */
    public OrderScreen() {
        this.Frame = new JFrame();
        initComponents();
    }
    public void ExportClient(Client Client1){
      LblName1.setText(Client1.getName());
      LblCpf1.setText(Client1.getCpf());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PnSize = new javax.swing.JPanel();
        BtnGiantSize = new javax.swing.JButton();
        Lbltitle = new javax.swing.JLabel();
        BtnSmallSize = new javax.swing.JButton();
        BtnFamilySize = new javax.swing.JButton();
        BtnAverageSize = new javax.swing.JButton();
        BtnBudSize = new javax.swing.JButton();
        TxtQtflavorsMod = new javax.swing.JTextField();
        TxtBorderSif = new javax.swing.JTextField();
        LblQtFlavors = new javax.swing.JLabel();
        LblSize = new javax.swing.JLabel();
        TxtSizeMod = new javax.swing.JTextField();
        BtnSelect = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        RGBorder = new javax.swing.JRadioButton();
        RGNoBorder = new javax.swing.JRadioButton();
        TxtBorderPriceMod = new javax.swing.JTextField();
        PnFlavors = new javax.swing.JPanel();
        BtnFlavor1 = new javax.swing.JButton();
        BtnFlavor3 = new javax.swing.JButton();
        BtnFlavor2 = new javax.swing.JButton();
        BtnFlavor4 = new javax.swing.JButton();
        BtnFlavor5 = new javax.swing.JButton();
        BtnFlavor7 = new javax.swing.JButton();
        BtnFlavor6 = new javax.swing.JButton();
        Btnflavor8 = new javax.swing.JButton();
        BtnFlavor9 = new javax.swing.JButton();
        LblFlavorTitle = new javax.swing.JLabel();
        LblSweetFlavor = new javax.swing.JLabel();
        LblSaltFlavor1 = new javax.swing.JLabel();
        LblFlavor1 = new javax.swing.JLabel();
        LblFlavor2 = new javax.swing.JLabel();
        LblFlavor3 = new javax.swing.JLabel();
        LblFlavor4 = new javax.swing.JLabel();
        LblFlavor5 = new javax.swing.JLabel();
        TxtFlavor5 = new javax.swing.JTextField();
        TxtFlavor1 = new javax.swing.JTextField();
        TxtFlavor2 = new javax.swing.JTextField();
        TxtFlavor3 = new javax.swing.JTextField();
        TxtFlavor4 = new javax.swing.JTextField();
        BtnSelectFlavor = new javax.swing.JButton();
        BtnCancelFlavor = new javax.swing.JButton();
        LblPlus = new javax.swing.JLabel();
        LblPlus1 = new javax.swing.JLabel();
        PnBorder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnBorder1 = new javax.swing.JButton();
        BtnBorder2 = new javax.swing.JButton();
        BtnBorder3 = new javax.swing.JButton();
        BtnBorder4 = new javax.swing.JButton();
        LblPriceBorder = new javax.swing.JLabel();
        TxtBorderFlavorsPMod = new javax.swing.JTextField();
        LblFlavors1 = new javax.swing.JLabel();
        TxtBordaFlavorsMod = new javax.swing.JLabel();
        TxtBorderFlavorssif = new javax.swing.JTextField();
        BtnCancelBorder = new javax.swing.JButton();
        BtnViewOrder = new javax.swing.JButton();
        PnOrder = new javax.swing.JPanel();
        LblSizePizzaMod = new javax.swing.JLabel();
        LblName1 = new javax.swing.JLabel();
        LblCpf = new javax.swing.JLabel();
        LblCpf1 = new javax.swing.JLabel();
        LblName2 = new javax.swing.JLabel();
        LblName3 = new javax.swing.JLabel();
        Lbltitlepiza1 = new javax.swing.JLabel();
        LblFlavorsPizzaMod = new javax.swing.JLabel();
        LblSizePizza2 = new javax.swing.JLabel();
        LblBorderPriceOrderB = new javax.swing.JLabel();
        LblFlavorsPizza2 = new javax.swing.JLabel();
        LblBorderpizza = new javax.swing.JLabel();
        Lbltitlepiza2 = new javax.swing.JLabel();
        Lbltitlepiza3 = new javax.swing.JLabel();
        Lbltitlepiza4 = new javax.swing.JLabel();
        LblWaterMod = new javax.swing.JLabel();
        LblCokepricemod = new javax.swing.JLabel();
        Lbltitlepiza6 = new javax.swing.JLabel();
        LblPriceunit1 = new javax.swing.JLabel();
        LblBorderPizzaMod1 = new javax.swing.JLabel();
        LblBorderPizzaMod2 = new javax.swing.JLabel();
        LblBorderPriceOrderAcr = new javax.swing.JLabel();
        LblBorderPizzaMod3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        LblBorderPizzaMod4 = new javax.swing.JLabel();
        LblBorderPriceOrderPizza = new javax.swing.JLabel();
        LblCokeMod = new javax.swing.JLabel();
        LblHeinekenmod = new javax.swing.JLabel();
        Lblpratzmod = new javax.swing.JLabel();
        LblPriceunit2 = new javax.swing.JLabel();
        Lblheinekenpricemod = new javax.swing.JLabel();
        LblPratzpricemod = new javax.swing.JLabel();
        LblWaterpricemod = new javax.swing.JLabel();
        PnBebidas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnCokeAdd = new javax.swing.JButton();
        BtnHeinekenAdd = new javax.swing.JButton();
        btnPratz = new javax.swing.JButton();
        BtnAgua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LblCoke = new javax.swing.JLabel();
        LblpriceCoke = new javax.swing.JLabel();
        LblHeinekenprice = new javax.swing.JLabel();
        LblHeineken = new javax.swing.JLabel();
        LblPratzPrice = new javax.swing.JLabel();
        LblPratz = new javax.swing.JLabel();
        LblWaterprice = new javax.swing.JLabel();
        LblWater = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BtnokDrink = new javax.swing.JButton();
        BtnCancelDrink = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setText("Coca-Cola 2 Lt");

        jLabel19.setText("Cerveja Heineken 330ml");

        jLabel22.setText("Suco Pratz 900ml");

        jLabel25.setText("Água Mineral 600ml");

        jLabel27.setText("Bebida");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 630, 600));
        setMinimumSize(new java.awt.Dimension(630, 600));
        setPreferredSize(new java.awt.Dimension(487, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(487, 370));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        PnSize.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PnSizeComponentShown(evt);
            }
        });
        PnSize.setLayout(null);

        BtnGiantSize.setText("Gigante");
        BtnGiantSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGiantSizeActionPerformed(evt);
            }
        });
        PnSize.add(BtnGiantSize);
        BtnGiantSize.setBounds(30, 60, 84, 22);

        Lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lbltitle.setText("Selecione o Tamanho da pizza");
        PnSize.add(Lbltitle);
        Lbltitle.setBounds(126, 6, 239, 25);

        BtnSmallSize.setText("Pequena");
        BtnSmallSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSmallSizeActionPerformed(evt);
            }
        });
        PnSize.add(BtnSmallSize);
        BtnSmallSize.setBounds(30, 180, 84, 22);

        BtnFamilySize.setText("Família");
        BtnFamilySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFamilySizeActionPerformed(evt);
            }
        });
        PnSize.add(BtnFamilySize);
        BtnFamilySize.setBounds(30, 100, 84, 22);

        BtnAverageSize.setText("Média");
        BtnAverageSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAverageSizeActionPerformed(evt);
            }
        });
        PnSize.add(BtnAverageSize);
        BtnAverageSize.setBounds(30, 140, 84, 22);

        BtnBudSize.setText("Broto");
        BtnBudSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBudSizeActionPerformed(evt);
            }
        });
        PnSize.add(BtnBudSize);
        BtnBudSize.setBounds(30, 220, 84, 22);

        TxtQtflavorsMod.setEditable(false);
        TxtQtflavorsMod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnSize.add(TxtQtflavorsMod);
        TxtQtflavorsMod.setBounds(280, 90, 194, 18);

        TxtBorderSif.setEditable(false);
        TxtBorderSif.setText("R$");
        TxtBorderSif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtBorderSif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBorderSifActionPerformed(evt);
            }
        });
        PnSize.add(TxtBorderSif);
        TxtBorderSif.setBounds(290, 150, 20, 18);

        LblQtFlavors.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblQtFlavors.setText("Quantidade de Sabores");
        LblQtFlavors.setAlignmentY(0.0F);
        PnSize.add(LblQtFlavors);
        LblQtFlavors.setBounds(130, 90, 140, 16);

        LblSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblSize.setText("Tamanho");
        LblSize.setAlignmentY(0.0F);
        PnSize.add(LblSize);
        LblSize.setBounds(130, 60, 140, 16);

        TxtSizeMod.setEditable(false);
        TxtSizeMod.setActionCommand("<Not Set>");
        TxtSizeMod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtSizeMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSizeModActionPerformed(evt);
            }
        });
        PnSize.add(TxtSizeMod);
        TxtSizeMod.setBounds(280, 60, 197, 18);

        BtnSelect.setText("Selecionar");
        BtnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelectActionPerformed(evt);
            }
        });
        PnSize.add(BtnSelect);
        BtnSelect.setBounds(350, 240, 100, 22);

        BtnCancel.setText("Cancelar");
        BtnCancel.setActionCommand("");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        PnSize.add(BtnCancel);
        BtnCancel.setBounds(250, 240, 90, 22);

        buttonGroup1.add(RGBorder);
        RGBorder.setText("Com Borda");
        RGBorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGBorderActionPerformed(evt);
            }
        });
        PnSize.add(RGBorder);
        RGBorder.setBounds(180, 120, 100, 20);

        buttonGroup1.add(RGNoBorder);
        RGNoBorder.setText("Sem Borda");
        RGNoBorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGNoBorderActionPerformed(evt);
            }
        });
        PnSize.add(RGNoBorder);
        RGNoBorder.setBounds(180, 150, 100, 20);

        TxtBorderPriceMod.setEditable(false);
        TxtBorderPriceMod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnSize.add(TxtBorderPriceMod);
        TxtBorderPriceMod.setBounds(320, 150, 170, 18);

        PnFlavors.setLayout(null);

        BtnFlavor1.setText("5 queijos");
        BtnFlavor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor1ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor1);
        BtnFlavor1.setBounds(160, 160, 100, 22);

        BtnFlavor3.setText("Cheddar");
        BtnFlavor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor3ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor3);
        BtnFlavor3.setBounds(20, 100, 110, 22);

        BtnFlavor2.setText("Frango Catupiry");
        BtnFlavor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor2ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor2);
        BtnFlavor2.setBounds(20, 130, 240, 22);

        BtnFlavor4.setText("Calabresa");
        BtnFlavor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor4ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor4);
        BtnFlavor4.setBounds(140, 100, 120, 22);

        BtnFlavor5.setText("Chocolate");
        BtnFlavor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor5ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor5);
        BtnFlavor5.setBounds(20, 230, 110, 22);

        BtnFlavor7.setText("Salmão com alcaparras");
        BtnFlavor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor7ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor7);
        BtnFlavor7.setBounds(20, 70, 240, 22);

        BtnFlavor6.setText("Prestígio");
        BtnFlavor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor6ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor6);
        BtnFlavor6.setBounds(20, 260, 110, 22);

        Btnflavor8.setText("Camarão");
        Btnflavor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnflavor8ActionPerformed(evt);
            }
        });
        PnFlavors.add(Btnflavor8);
        Btnflavor8.setBounds(20, 160, 130, 22);

        BtnFlavor9.setText("Abacaxi com Canela");
        BtnFlavor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlavor9ActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnFlavor9);
        BtnFlavor9.setBounds(20, 290, 180, 22);

        LblFlavorTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblFlavorTitle.setText("Selecione os sabores desejados");
        PnFlavors.add(LblFlavorTitle);
        LblFlavorTitle.setBounds(20, 10, 270, 25);

        LblSweetFlavor.setText("Sabores Doces");
        PnFlavors.add(LblSweetFlavor);
        LblSweetFlavor.setBounds(20, 200, 100, 16);

        LblSaltFlavor1.setText("Sabores Salgados");
        PnFlavors.add(LblSaltFlavor1);
        LblSaltFlavor1.setBounds(20, 50, 100, 16);

        LblFlavor1.setText("Sabor 1:");
        PnFlavors.add(LblFlavor1);
        LblFlavor1.setBounds(290, 50, 50, 16);

        LblFlavor2.setText("Sabor 2:");
        PnFlavors.add(LblFlavor2);
        LblFlavor2.setBounds(290, 80, 50, 16);

        LblFlavor3.setText("Sabor 3:");
        PnFlavors.add(LblFlavor3);
        LblFlavor3.setBounds(290, 110, 50, 16);

        LblFlavor4.setText("Sabor 4:");
        PnFlavors.add(LblFlavor4);
        LblFlavor4.setBounds(290, 140, 50, 16);

        LblFlavor5.setText("Sabor 5:");
        PnFlavors.add(LblFlavor5);
        LblFlavor5.setBounds(290, 170, 50, 16);

        TxtFlavor5.setEditable(false);
        TxtFlavor5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnFlavors.add(TxtFlavor5);
        TxtFlavor5.setBounds(350, 170, 140, 18);

        TxtFlavor1.setEditable(false);
        TxtFlavor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnFlavors.add(TxtFlavor1);
        TxtFlavor1.setBounds(350, 50, 140, 18);

        TxtFlavor2.setEditable(false);
        TxtFlavor2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnFlavors.add(TxtFlavor2);
        TxtFlavor2.setBounds(350, 80, 140, 18);

        TxtFlavor3.setEditable(false);
        TxtFlavor3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnFlavors.add(TxtFlavor3);
        TxtFlavor3.setBounds(350, 110, 140, 18);

        TxtFlavor4.setEditable(false);
        TxtFlavor4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PnFlavors.add(TxtFlavor4);
        TxtFlavor4.setBounds(350, 140, 140, 18);

        BtnSelectFlavor.setText("Seguir");
        BtnSelectFlavor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelectFlavorActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnSelectFlavor);
        BtnSelectFlavor.setBounds(390, 300, 72, 22);

        BtnCancelFlavor.setText("Cancelar");
        BtnCancelFlavor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelFlavorActionPerformed(evt);
            }
        });
        PnFlavors.add(BtnCancelFlavor);
        BtnCancelFlavor.setBounds(285, 300, 90, 22);
        PnFlavors.add(LblPlus);
        LblPlus.setBounds(360, 220, 110, 20);

        LblPlus1.setText("Acréscimo:");
        PnFlavors.add(LblPlus1);
        LblPlus1.setBounds(290, 220, 70, 16);

        PnBorder.setMinimumSize(new java.awt.Dimension(389, 292));
        PnBorder.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione a sua borda");
        PnBorder.add(jLabel1);
        jLabel1.setBounds(20, 10, 340, 25);

        BtnBorder1.setText("Cheddar");
        BtnBorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorder1ActionPerformed(evt);
            }
        });
        PnBorder.add(BtnBorder1);
        BtnBorder1.setBounds(20, 50, 100, 22);

        BtnBorder2.setText("Catupiry");
        BtnBorder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorder2ActionPerformed(evt);
            }
        });
        PnBorder.add(BtnBorder2);
        BtnBorder2.setBounds(20, 80, 100, 22);

        BtnBorder3.setText("<html> Metade Nutella <br> Metade Doce de Leite");
        BtnBorder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorder3ActionPerformed(evt);
            }
        });
        PnBorder.add(BtnBorder3);
        BtnBorder3.setBounds(20, 110, 150, 60);

        BtnBorder4.setText("Nutella");
        BtnBorder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorder4ActionPerformed(evt);
            }
        });
        PnBorder.add(BtnBorder4);
        BtnBorder4.setBounds(20, 180, 100, 22);

        LblPriceBorder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPriceBorder.setText("Valor Acréscimo");
        PnBorder.add(LblPriceBorder);
        LblPriceBorder.setBounds(130, 50, 100, 16);

        TxtBorderFlavorsPMod.setEditable(false);
        TxtBorderFlavorsPMod.setText("R$");
        TxtBorderFlavorsPMod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtBorderFlavorsPMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBorderFlavorsPModActionPerformed(evt);
            }
        });
        PnBorder.add(TxtBorderFlavorsPMod);
        TxtBorderFlavorsPMod.setBounds(240, 50, 20, 18);

        LblFlavors1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblFlavors1.setText("Sabor Borda");
        PnBorder.add(LblFlavors1);
        LblFlavors1.setBounds(140, 80, 90, 16);

        TxtBordaFlavorsMod.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TxtBordaFlavorsMod.setVerifyInputWhenFocusTarget(false);
        TxtBordaFlavorsMod.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PnBorder.add(TxtBordaFlavorsMod);
        TxtBordaFlavorsMod.setBounds(240, 80, 190, 80);

        TxtBorderFlavorssif.setEditable(false);
        TxtBorderFlavorssif.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtBorderFlavorssif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBorderFlavorssifActionPerformed(evt);
            }
        });
        PnBorder.add(TxtBorderFlavorssif);
        TxtBorderFlavorssif.setBounds(270, 50, 110, 20);

        BtnCancelBorder.setText("Cancelar");
        BtnCancelBorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelBorderActionPerformed(evt);
            }
        });
        PnBorder.add(BtnCancelBorder);
        BtnCancelBorder.setBounds(170, 210, 76, 22);

        BtnViewOrder.setText("Visualizar pedido");
        BtnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewOrderActionPerformed(evt);
            }
        });
        PnBorder.add(BtnViewOrder);
        BtnViewOrder.setBounds(260, 210, 170, 22);

        PnOrder.setAutoscrolls(true);
        PnOrder.setMinimumSize(new java.awt.Dimension(630, 600));
        PnOrder.setName(""); // NOI18N
        PnOrder.setPreferredSize(new java.awt.Dimension(490, 476));
        PnOrder.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PnOrderComponentShown(evt);
            }
        });
        PnOrder.setLayout(null);
        PnOrder.add(LblSizePizzaMod);
        LblSizePizzaMod.setBounds(130, 140, 480, 20);

        LblName1.setText("Nome:");
        PnOrder.add(LblName1);
        LblName1.setBounds(80, 50, 370, 16);

        LblCpf.setText("Cpf:");
        PnOrder.add(LblCpf);
        LblCpf.setBounds(40, 70, 22, 16);

        LblCpf1.setText("Cpf:");
        PnOrder.add(LblCpf1);
        LblCpf1.setBounds(70, 70, 390, 16);

        LblName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblName2.setText("Seu Pedido");
        PnOrder.add(LblName2);
        LblName2.setBounds(190, 10, 110, 40);

        LblName3.setText("Nome:");
        PnOrder.add(LblName3);
        LblName3.setBounds(40, 50, 36, 16);

        Lbltitlepiza1.setText("Valor total Bebida:");
        PnOrder.add(Lbltitlepiza1);
        Lbltitlepiza1.setBounds(370, 400, 110, 16);
        PnOrder.add(LblFlavorsPizzaMod);
        LblFlavorsPizzaMod.setBounds(130, 160, 470, 20);

        LblSizePizza2.setText("Tamanho:");
        PnOrder.add(LblSizePizza2);
        LblSizePizza2.setBounds(26, 140, 70, 16);

        LblBorderPriceOrderB.setText("Valor:");
        PnOrder.add(LblBorderPriceOrderB);
        LblBorderPriceOrderB.setBounds(490, 210, 80, 16);

        LblFlavorsPizza2.setText("Sabores:");
        PnOrder.add(LblFlavorsPizza2);
        LblFlavorsPizza2.setBounds(36, 160, 70, 16);

        LblBorderpizza.setText("Borda:");
        PnOrder.add(LblBorderpizza);
        LblBorderpizza.setBounds(46, 180, 60, 16);

        Lbltitlepiza2.setText("Pizza");
        PnOrder.add(Lbltitlepiza2);
        Lbltitlepiza2.setBounds(26, 120, 40, 16);

        Lbltitlepiza3.setText("Bebida");
        PnOrder.add(Lbltitlepiza3);
        Lbltitlepiza3.setBounds(30, 270, 60, 16);

        Lbltitlepiza4.setText("Bebida:");
        PnOrder.add(Lbltitlepiza4);
        Lbltitlepiza4.setBounds(50, 300, 60, 16);

        LblWaterMod.setText("Bebida:");
        PnOrder.add(LblWaterMod);
        LblWaterMod.setBounds(130, 360, 260, 16);

        LblCokepricemod.setText("Valor unit:");
        PnOrder.add(LblCokepricemod);
        LblCokepricemod.setBounds(490, 300, 80, 16);

        Lbltitlepiza6.setText("Valor total do pedido:");
        PnOrder.add(Lbltitlepiza6);
        Lbltitlepiza6.setBounds(350, 450, 130, 16);

        LblPriceunit1.setText("Valor unit:");
        PnOrder.add(LblPriceunit1);
        LblPriceunit1.setBounds(500, 450, 80, 16);

        LblBorderPizzaMod1.setText("Pizza");
        LblBorderPizzaMod1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PnOrder.add(LblBorderPizzaMod1);
        LblBorderPizzaMod1.setBounds(130, 180, 130, 50);

        LblBorderPizzaMod2.setText("Valor Borda:");
        PnOrder.add(LblBorderPizzaMod2);
        LblBorderPizzaMod2.setBounds(400, 210, 90, 16);

        LblBorderPriceOrderAcr.setText("Valor:");
        PnOrder.add(LblBorderPriceOrderAcr);
        LblBorderPriceOrderAcr.setBounds(490, 230, 80, 16);

        LblBorderPizzaMod3.setText("Acréscimos Sabores:");
        PnOrder.add(LblBorderPizzaMod3);
        LblBorderPizzaMod3.setBounds(350, 230, 130, 16);

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------");
        PnOrder.add(jLabel2);
        jLabel2.setBounds(20, 420, 580, 16);

        jLabel3.setText("--------------------------------------------------------------------------------------------------------------------------------------");
        PnOrder.add(jLabel3);
        jLabel3.setBounds(10, 90, 590, 16);

        jLabel4.setText("------------------------------------------------------------------------------------------------------------------------------------------");
        PnOrder.add(jLabel4);
        jLabel4.setBounds(10, 250, 590, 16);

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        PnOrder.add(Confirmar);
        Confirmar.setBounds(480, 490, 100, 22);

        LblBorderPizzaMod4.setText("Valor Pizza:");
        PnOrder.add(LblBorderPizzaMod4);
        LblBorderPizzaMod4.setBounds(400, 190, 80, 16);

        LblBorderPriceOrderPizza.setText("Valor:");
        PnOrder.add(LblBorderPriceOrderPizza);
        LblBorderPriceOrderPizza.setBounds(490, 190, 80, 16);

        LblCokeMod.setText("Bebida:");
        PnOrder.add(LblCokeMod);
        LblCokeMod.setBounds(130, 300, 250, 16);

        LblHeinekenmod.setText("Bebida:");
        PnOrder.add(LblHeinekenmod);
        LblHeinekenmod.setBounds(130, 320, 260, 16);

        Lblpratzmod.setText("Bebida:");
        PnOrder.add(Lblpratzmod);
        Lblpratzmod.setBounds(130, 340, 260, 16);

        LblPriceunit2.setText("Valor unit:");
        PnOrder.add(LblPriceunit2);
        LblPriceunit2.setBounds(490, 400, 90, 16);

        Lblheinekenpricemod.setText("Valor unit:");
        PnOrder.add(Lblheinekenpricemod);
        Lblheinekenpricemod.setBounds(490, 320, 60, 16);

        LblPratzpricemod.setText("Valor unit:");
        PnOrder.add(LblPratzpricemod);
        LblPratzpricemod.setBounds(490, 340, 80, 16);

        LblWaterpricemod.setText("Valor unit:");
        PnOrder.add(LblWaterpricemod);
        LblWaterpricemod.setBounds(490, 360, 80, 16);

        PnBebidas.setMinimumSize(new java.awt.Dimension(401, 427));
        PnBebidas.setPreferredSize(new java.awt.Dimension(397, 290));
        PnBebidas.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Bebidas");
        PnBebidas.add(jLabel5);
        jLabel5.setBounds(230, -10, 76, 50);

        BtnCokeAdd.setText("1");
        BtnCokeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCokeAddActionPerformed(evt);
            }
        });
        PnBebidas.add(BtnCokeAdd);
        BtnCokeAdd.setBounds(10, 40, 60, 22);

        BtnHeinekenAdd.setText("2");
        BtnHeinekenAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHeinekenAddActionPerformed(evt);
            }
        });
        PnBebidas.add(BtnHeinekenAdd);
        BtnHeinekenAdd.setBounds(10, 70, 60, 22);

        btnPratz.setText("3");
        btnPratz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratzActionPerformed(evt);
            }
        });
        PnBebidas.add(btnPratz);
        btnPratz.setBounds(10, 100, 60, 22);

        BtnAgua.setText("4");
        BtnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAguaActionPerformed(evt);
            }
        });
        PnBebidas.add(BtnAgua);
        BtnAgua.setBounds(10, 130, 60, 22);

        jLabel6.setText("3,50");
        PnBebidas.add(jLabel6);
        jLabel6.setBounds(280, 130, 60, 16);

        jLabel7.setText("Coca-Cola 2 Lt");
        PnBebidas.add(jLabel7);
        jLabel7.setBounds(120, 40, 120, 16);

        jLabel8.setText("9,50");
        PnBebidas.add(jLabel8);
        jLabel8.setBounds(280, 40, 60, 16);

        jLabel9.setText("Cerveja Heineken 330ml");
        PnBebidas.add(jLabel9);
        jLabel9.setBounds(120, 70, 140, 16);

        jLabel10.setText("6,50");
        PnBebidas.add(jLabel10);
        jLabel10.setBounds(280, 70, 60, 16);

        jLabel11.setText("Suco Pratz 900ml");
        PnBebidas.add(jLabel11);
        jLabel11.setBounds(120, 100, 120, 16);

        jLabel12.setText("12,50");
        PnBebidas.add(jLabel12);
        jLabel12.setBounds(280, 100, 60, 16);

        jLabel13.setText("Água Mineral 600ml");
        PnBebidas.add(jLabel13);
        jLabel13.setBounds(120, 130, 140, 16);
        PnBebidas.add(LblCoke);
        LblCoke.setBounds(350, 40, 70, 20);
        PnBebidas.add(LblpriceCoke);
        LblpriceCoke.setBounds(410, 40, 60, 20);
        PnBebidas.add(LblHeinekenprice);
        LblHeinekenprice.setBounds(410, 70, 80, 20);
        PnBebidas.add(LblHeineken);
        LblHeineken.setBounds(350, 70, 60, 20);
        PnBebidas.add(LblPratzPrice);
        LblPratzPrice.setBounds(410, 100, 80, 20);
        PnBebidas.add(LblPratz);
        LblPratz.setBounds(350, 100, 60, 20);
        PnBebidas.add(LblWaterprice);
        LblWaterprice.setBounds(410, 130, 90, 20);
        PnBebidas.add(LblWater);
        LblWater.setBounds(350, 130, 70, 20);

        jLabel26.setText("Valor");
        PnBebidas.add(jLabel26);
        jLabel26.setBounds(410, 10, 60, 16);

        jLabel28.setText("Qtd");
        PnBebidas.add(jLabel28);
        jLabel28.setBounds(350, 10, 50, 16);

        BtnokDrink.setText("Prosseguir");
        BtnokDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnokDrinkActionPerformed(evt);
            }
        });
        PnBebidas.add(BtnokDrink);
        BtnokDrink.setBounds(270, 190, 100, 22);

        BtnCancelDrink.setText("Cancelar");
        BtnCancelDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelDrinkActionPerformed(evt);
            }
        });
        PnBebidas.add(BtnCancelDrink);
        BtnCancelDrink.setBounds(170, 190, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnSize, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnFlavors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 80, Short.MAX_VALUE)
                    .addComponent(PnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGap(0, 81, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 76, Short.MAX_VALUE)
                    .addComponent(PnBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGap(0, 77, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnFlavors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 104, Short.MAX_VALUE)
                    .addComponent(PnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGap(0, 104, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 57, Short.MAX_VALUE)
                    .addComponent(PnBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGap(0, 59, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGiantSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGiantSizeActionPerformed
        Border = 80.00; 
        NoBorder = 75.00;
        Flavors = 5;
        Size = "Gigante";
        TxtSizeMod.setText(Size);
        TxtQtflavorsMod.setText("Até " + Flavors + " Sabores");
        RGBorder.setSelected(true);
        RGBorderActionPerformed(evt);
    }//GEN-LAST:event_BtnGiantSizeActionPerformed

    private void BtnSmallSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSmallSizeActionPerformed
        Border = 44.50; 
        NoBorder = 42.00;
        Flavors = 3;
         Size = "Pequena";
        TxtSizeMod.setText(Size);
        TxtQtflavorsMod.setText("Até " + Flavors + " Sabores");
        RGBorder.setSelected(true);
        RGBorderActionPerformed(evt);
    }//GEN-LAST:event_BtnSmallSizeActionPerformed

    private void BtnFamilySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFamilySizeActionPerformed
        Border = 69.50; 
        NoBorder = 66.00;
        Flavors = 4;
        Size = "Família";
        TxtSizeMod.setText(Size);
        TxtQtflavorsMod.setText("Até " + Flavors + " Sabores");
        RGBorder.setSelected(true);
        RGBorderActionPerformed(evt);
    }//GEN-LAST:event_BtnFamilySizeActionPerformed

    private void BtnAverageSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAverageSizeActionPerformed
        Border = 56.50; 
        NoBorder = 52.00;
        Flavors = 3;
        Size = "Média";
        TxtSizeMod.setText(Size);
        TxtQtflavorsMod.setText("Até " + Flavors + " Sabores");
        RGBorder.setSelected(true);
        RGBorderActionPerformed(evt);
    }//GEN-LAST:event_BtnAverageSizeActionPerformed

    private void BtnBudSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBudSizeActionPerformed
        NoBorder = 28.00;
        Flavors = 2;
        Size = "Broto";
        TxtSizeMod.setText(Size);
        TxtQtflavorsMod.setText("Até " + Flavors + " Sabores");
        RGNoBorder.setSelected(true);
        RGNoBorderActionPerformed(evt);
    }//GEN-LAST:event_BtnBudSizeActionPerformed

    private void TxtSizeModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSizeModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSizeModActionPerformed

    private void BtnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelectActionPerformed
        if ((TxtSizeMod.getText().length() > 0) && !(TxtBorderSif.getText().equals("Não disponível")) ){
           //Pizza Pizza1 = new Pizza();
           Pizza1.setSize(Size); 
           Pizza1.setQtFlavors(Flavors);
           Pizza1.setPrice(Price);
           PnFlavors.setVisible(true);
           PnFlavors.setBounds(0,0,500,370);
           PnSize.setVisible(false);
           switch (Flavors){
               case 3: TxtFlavor3.setVisible(true);
                       LblFlavor3.setVisible(true);
                       break;
               
               case 4: TxtFlavor3.setVisible(true);
                       TxtFlavor4.setVisible(true);
                       LblFlavor3.setVisible(true);
                       LblFlavor4.setVisible(true);
                       break;
                       
               case 5: TxtFlavor3.setVisible(true);
                       TxtFlavor4.setVisible(true);
                       TxtFlavor5.setVisible(true);
                       LblFlavor3.setVisible(true);
                       LblFlavor4.setVisible(true);
                       LblFlavor5.setVisible(true);
                       break;
           }
           
        }else{
          JOptionPane.showMessageDialog(null, "Selecione uma opção valida para continuar", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSelectActionPerformed

    private void BtnCancelFlavorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelFlavorActionPerformed
           PnSize.setVisible(true);
           PnSize.setBounds(0, 0, 464, 282);
           PnFlavors.setVisible(false);
           ClearAll();
           StartScreen();
           
    }//GEN-LAST:event_BtnCancelFlavorActionPerformed

    private void PnSizeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PnSizeComponentShown
        
    }//GEN-LAST:event_PnSizeComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        StartScreen();
    }//GEN-LAST:event_formComponentShown

    private void BtnFlavor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor7ActionPerformed
       if (Flavors > CountFlavors){ 
            CountFlavors++; 
        Object[] options = {"Sim", "Não"};
        int op = JOptionPane.showOptionDialog(null, "Este sabor tem acréscimo de R$4,00 no valor \n Deseja continuar?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
       if (op == 0){         
        SelectFlavor(BtnFlavor7.getText());
        if (LblPlus.getText().equals("")){
        LblPlus.setText(String.valueOf(4.00));
        PriceFlavor = PriceFlavor + 4.00;
        
        }else{
            LblPlus.setText(String.valueOf(Double.parseDouble(LblPlus.getText()) + 4.00));
        }Price = Price + 4.00; 
       
       }else{
           CountFlavors--;
       }
       }else{
           JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");
       }
    }//GEN-LAST:event_BtnFlavor7ActionPerformed
   
    private void BtnSelectFlavorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelectFlavorActionPerformed

        if ((Pizza1.getSize().equals("Broto") && (RGBorder.isSelected())) || (RGNoBorder.isSelected())){
            PnBebidas.setVisible(true);
            PnFlavors.setVisible(false);
            LblBorderPriceOrderB.setText("");
             LblBorderPizzaMod1.setText("Borda não selecionada \n Não disponível");
          }else{
           PnBorder.setVisible(true);
           PnBorder.setBounds(0,0,500,370);
           PnFlavors.setVisible(false);
           BtnBorder1.setVisible(true);
           BtnBorder2.setVisible(true);
           BtnBorder3.setVisible(true);
           BtnBorder4.setVisible(true);
          }
                   
    }//GEN-LAST:event_BtnSelectFlavorActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnFlavor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor3ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        Object[] options = {"Sim", "Não"};
        int op = JOptionPane.showOptionDialog(null, "Este sabor tem acréscimo de R$3,50 no valor \n Deseja continuar?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
       if (op == 0){
        PriceFlavor = PriceFlavor + 3.50;
        SelectFlavor(BtnFlavor3.getText());
        if (LblPlus.getText().equals("")){
        LblPlus.setText(String.valueOf(3.50));
        }else{
            LblPlus.setText(String.valueOf(Double.parseDouble(LblPlus.getText()) + 3.50));
        }
        Price = Price + 3.50;
       }else{
           CountFlavors--;
       }
       }else{
           JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores"); 
        }
    }//GEN-LAST:event_BtnFlavor3ActionPerformed

    private void BtnFlavor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor4ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        SelectFlavor(BtnFlavor4.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor4ActionPerformed

    private void BtnFlavor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor2ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        SelectFlavor(BtnFlavor2.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor2ActionPerformed

    private void Btnflavor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnflavor8ActionPerformed
       if (Flavors > CountFlavors){ 
            CountFlavors++; 
        Object[] options = {"Sim", "Não"};
        int op = JOptionPane.showOptionDialog(null, "Este sabor tem acréscimo de R$4,50 no valor \n Deseja continuar?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
       if (op == 0){ 
        SelectFlavor(Btnflavor8.getText());
        Price = Price + 4.50;
        PriceFlavor = PriceFlavor + 4.50;
        if (LblPlus.getText().equals("")){
        LblPlus.setText(String.valueOf(4.50));
        }else{
            LblPlus.setText(String.valueOf(Double.parseDouble(LblPlus.getText()) + 4.50));
        }
       }else{
           CountFlavors--;
       }
       }else{
           JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_Btnflavor8ActionPerformed
    
    private void BtnFlavor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor1ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        SelectFlavor(BtnFlavor1.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor1ActionPerformed

    private void BtnFlavor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor5ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        SelectFlavor(BtnFlavor5.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor5ActionPerformed

    private void BtnFlavor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor6ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++; 
        SelectFlavor(BtnFlavor6.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor6ActionPerformed

    private void BtnFlavor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlavor9ActionPerformed
        if (Flavors > CountFlavors){ 
            CountFlavors++;
        SelectFlavor(BtnFlavor9.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Você atingiu o maximo de sabores");  
        }
    }//GEN-LAST:event_BtnFlavor9ActionPerformed

    private void BtnBorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorder1ActionPerformed
        TxtBordaFlavorsMod.setText(BtnBorder1.getText());
        LblPriceBorder.setVisible(false);
        TxtBorderFlavorssif.setVisible(false);
        PriceBorder = 0;
        TxtBorderFlavorsPMod.setVisible(false);
    }//GEN-LAST:event_BtnBorder1ActionPerformed

    private void BtnBorder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorder2ActionPerformed
       TxtBordaFlavorsMod.setText(BtnBorder2.getText());
       LblPriceBorder.setVisible(false);
       TxtBorderFlavorssif.setVisible(false);
       PriceBorder = 0;
       TxtBorderFlavorsPMod.setVisible(false);
    }//GEN-LAST:event_BtnBorder2ActionPerformed

    private void BtnBorder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorder3ActionPerformed
        Object[] options = {"Sim", "Não"};
        int op = JOptionPane.showOptionDialog(null, "Este sabor tem acréscimo de R$3,00 no valor \n Deseja continuar?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
       if (op == 0){ 
        BorderPrice1 = 3.00;
        LblPriceBorder.setVisible(true);
        TxtBordaFlavorsMod.setText(BtnBorder3.getText()/*"<html>Metade Nutela <br> Metade Doce de Leite"*/);
        TxtBorderFlavorssif.setText(String.valueOf(BorderPrice1));
        TxtBorderFlavorsPMod.setText("R$");     
        PriceBorder = BorderPrice1;
        }
    }//GEN-LAST:event_BtnBorder3ActionPerformed

    private void BtnBorder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorder4ActionPerformed
        Object[] options = {"Sim", "Não"};
        int op = JOptionPane.showOptionDialog(null, "Este sabor tem acréscimo de R$2,00 no valor \n Deseja continuar?", "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
       if (op == 0){        
        BorderPrice2 = 2.00;
        LblPriceBorder.setVisible(true);
        TxtBordaFlavorsMod.setText(BtnBorder4.getText());
        TxtBorderFlavorssif.setText(String.valueOf(BorderPrice2));
        TxtBorderFlavorsPMod.setText("R$");
        PriceBorder = BorderPrice2;
        }
    }//GEN-LAST:event_BtnBorder4ActionPerformed

    private void RGBorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGBorderActionPerformed
        if ((RGBorder.isSelected()) && (!TxtSizeMod.getText().equals("Broto"))){
          TxtBorderPriceMod.setText(String.valueOf(Border));
          Price = Border;
          TxtBorderSif.setVisible(true);
        }else{
            TxtBorderSif.setVisible(false);
            TxtBorderPriceMod.setText("Não disponível");
        }
    }//GEN-LAST:event_RGBorderActionPerformed

    private void RGNoBorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGNoBorderActionPerformed
        if (RGNoBorder.isSelected()){
          TxtBorderSif.setVisible(true);
          TxtBorderPriceMod.setText(String.valueOf(NoBorder));
          Price = NoBorder;
        }
    }//GEN-LAST:event_RGNoBorderActionPerformed

    private void TxtBorderSifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBorderSifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBorderSifActionPerformed

    private void TxtBorderFlavorsPModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBorderFlavorsPModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBorderFlavorsPModActionPerformed

    private void TxtBorderFlavorssifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBorderFlavorssifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBorderFlavorssifActionPerformed

    private void BtnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewOrderActionPerformed
        Price = Price + PriceBorder;
        Pizza1.setBorder(TxtBordaFlavorsMod.getText());
        Pizza1.setPrice(Price);
        PnBorder.setVisible(false);
        PnBebidas.setVisible(true);
    }//GEN-LAST:event_BtnViewOrderActionPerformed

    private void BtnCancelBorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelBorderActionPerformed
           PnSize.setVisible(true);
           PnSize.setBounds(0, 0, 464, 282);
           PnFlavors.setVisible(false);
           ClearAll();
           StartScreen();
    }//GEN-LAST:event_BtnCancelBorderActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        JOptionPane.showMessageDialog(null, "Obrigado por utilizar nossos serviços!", "Obrigado!", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void PnOrderComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PnOrderComponentShown
        //ShowPNOrder
        LblSizePizzaMod.setText(Pizza1.getSize());
        LblBorderPriceOrderPizza.setText(TxtBorderPriceMod.getText());
        for (int i = 0; i < flavor.size(); i++){
            if (i == 0){
        LblFlavorsPizzaMod.setText(flavor.get(i));
            }else{
        LblFlavorsPizzaMod.setText(LblFlavorsPizzaMod.getText()+ ", " + flavor.get(i));        
            }
        LblBorderPriceOrderB.setText("R$"+String.valueOf(PriceBorder));
        LblBorderPizzaMod1.setText(TxtBordaFlavorsMod.getText());
        LblBorderPriceOrderAcr.setText("R$"+String.valueOf(PriceFlavor));
        LblPriceunit2.setText(String.valueOf(somabebidas(pricecoke,priceheineken,pricewater,pricepratz)));
        LblPriceunit1.setText(String.valueOf(SomaTotal(PriceFlavor,PriceBorder,Double.valueOf(TxtBorderPriceMod.getText()), Double.valueOf(LblPriceunit2.getText()))));
        
    }
    }//GEN-LAST:event_PnOrderComponentShown

    private void BtnCokeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCokeAddActionPerformed

        c = c + 1;
        pricecoke = pricecoke + 9.50;
        LblCoke.setText(String.valueOf(c));
        LblpriceCoke.setText(String.valueOf(pricecoke));
    }//GEN-LAST:event_BtnCokeAddActionPerformed

    private void BtnHeinekenAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHeinekenAddActionPerformed
        h = h + 1;
        priceheineken = priceheineken + 6.50;
        LblHeineken.setText(String.valueOf(h));
        LblHeinekenprice.setText(String.valueOf(priceheineken));
    }//GEN-LAST:event_BtnHeinekenAddActionPerformed

    private void btnPratzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratzActionPerformed
        p = p + 1;
        pricepratz = pricepratz + 12.50;
        LblPratz.setText(String.valueOf(p));
        LblPratzPrice.setText(String.valueOf(pricepratz));
    }//GEN-LAST:event_btnPratzActionPerformed

    private void BtnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAguaActionPerformed
        w = w + 1;
        pricewater = pricewater + 3.50;
        LblWater.setText(String.valueOf(w));
        LblWaterprice.setText(String.valueOf(pricewater));
    }//GEN-LAST:event_BtnAguaActionPerformed

    private void BtnokDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnokDrinkActionPerformed
        PnBebidas.setVisible(false);
        PnOrder.setVisible(true);
        LblCokepricemod.setText(LblpriceCoke.getText());
        Lblheinekenpricemod.setText(LblHeinekenprice.getText());
        LblPratzpricemod.setText(LblPratzPrice.getText());
        LblWaterpricemod.setText(LblWaterprice.getText());
        LblCokeMod.setText(c + " Unidades ........ " + jLabel15.getText());
        LblHeinekenmod.setText(h + " Unidades ........ " +jLabel19.getText());
        Lblpratzmod.setText(p + " Unidades ........ " + jLabel22.getText());
        LblWaterMod.setText(w + " Unidades ........ " + jLabel25.getText());
    }//GEN-LAST:event_BtnokDrinkActionPerformed

    private void BtnCancelDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelDrinkActionPerformed
           PnSize.setVisible(true);
           PnSize.setBounds(0, 0, 464, 282);
           PnFlavors.setVisible(false);
           ClearAll();
           StartScreen();
    }//GEN-LAST:event_BtnCancelDrinkActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgua;
    private javax.swing.JButton BtnAverageSize;
    private javax.swing.JButton BtnBorder1;
    private javax.swing.JButton BtnBorder2;
    private javax.swing.JButton BtnBorder3;
    private javax.swing.JButton BtnBorder4;
    private javax.swing.JButton BtnBudSize;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnCancelBorder;
    private javax.swing.JButton BtnCancelDrink;
    private javax.swing.JButton BtnCancelFlavor;
    private javax.swing.JButton BtnCokeAdd;
    private javax.swing.JButton BtnFamilySize;
    private javax.swing.JButton BtnFlavor1;
    private javax.swing.JButton BtnFlavor2;
    private javax.swing.JButton BtnFlavor3;
    private javax.swing.JButton BtnFlavor4;
    private javax.swing.JButton BtnFlavor5;
    private javax.swing.JButton BtnFlavor6;
    private javax.swing.JButton BtnFlavor7;
    private javax.swing.JButton BtnFlavor9;
    private javax.swing.JButton BtnGiantSize;
    private javax.swing.JButton BtnHeinekenAdd;
    private javax.swing.JButton BtnSelect;
    private javax.swing.JButton BtnSelectFlavor;
    private javax.swing.JButton BtnSmallSize;
    private javax.swing.JButton BtnViewOrder;
    private javax.swing.JButton Btnflavor8;
    private javax.swing.JButton BtnokDrink;
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel LblBorderPizzaMod1;
    private javax.swing.JLabel LblBorderPizzaMod2;
    private javax.swing.JLabel LblBorderPizzaMod3;
    private javax.swing.JLabel LblBorderPizzaMod4;
    private javax.swing.JLabel LblBorderPriceOrderAcr;
    private javax.swing.JLabel LblBorderPriceOrderB;
    private javax.swing.JLabel LblBorderPriceOrderPizza;
    private javax.swing.JLabel LblBorderpizza;
    private javax.swing.JLabel LblCoke;
    private javax.swing.JLabel LblCokeMod;
    private javax.swing.JLabel LblCokepricemod;
    private javax.swing.JLabel LblCpf;
    private javax.swing.JLabel LblCpf1;
    private javax.swing.JLabel LblFlavor1;
    private javax.swing.JLabel LblFlavor2;
    private javax.swing.JLabel LblFlavor3;
    private javax.swing.JLabel LblFlavor4;
    private javax.swing.JLabel LblFlavor5;
    private javax.swing.JLabel LblFlavorTitle;
    private javax.swing.JLabel LblFlavors1;
    private javax.swing.JLabel LblFlavorsPizza2;
    private javax.swing.JLabel LblFlavorsPizzaMod;
    private javax.swing.JLabel LblHeineken;
    private javax.swing.JLabel LblHeinekenmod;
    private javax.swing.JLabel LblHeinekenprice;
    private javax.swing.JLabel LblName1;
    private javax.swing.JLabel LblName2;
    private javax.swing.JLabel LblName3;
    private javax.swing.JLabel LblPlus;
    private javax.swing.JLabel LblPlus1;
    private javax.swing.JLabel LblPratz;
    private javax.swing.JLabel LblPratzPrice;
    private javax.swing.JLabel LblPratzpricemod;
    private javax.swing.JLabel LblPriceBorder;
    private javax.swing.JLabel LblPriceunit1;
    private javax.swing.JLabel LblPriceunit2;
    private javax.swing.JLabel LblQtFlavors;
    private javax.swing.JLabel LblSaltFlavor1;
    private javax.swing.JLabel LblSize;
    private javax.swing.JLabel LblSizePizza2;
    private javax.swing.JLabel LblSizePizzaMod;
    private javax.swing.JLabel LblSweetFlavor;
    private javax.swing.JLabel LblWater;
    private javax.swing.JLabel LblWaterMod;
    private javax.swing.JLabel LblWaterprice;
    private javax.swing.JLabel LblWaterpricemod;
    private javax.swing.JLabel Lblheinekenpricemod;
    private javax.swing.JLabel Lblpratzmod;
    private javax.swing.JLabel LblpriceCoke;
    private javax.swing.JLabel Lbltitle;
    private javax.swing.JLabel Lbltitlepiza1;
    private javax.swing.JLabel Lbltitlepiza2;
    private javax.swing.JLabel Lbltitlepiza3;
    private javax.swing.JLabel Lbltitlepiza4;
    private javax.swing.JLabel Lbltitlepiza6;
    private javax.swing.JPanel PnBebidas;
    private javax.swing.JPanel PnBorder;
    private javax.swing.JPanel PnFlavors;
    private javax.swing.JPanel PnOrder;
    private javax.swing.JPanel PnSize;
    private javax.swing.JRadioButton RGBorder;
    private javax.swing.JRadioButton RGNoBorder;
    private javax.swing.JLabel TxtBordaFlavorsMod;
    private javax.swing.JTextField TxtBorderFlavorsPMod;
    private javax.swing.JTextField TxtBorderFlavorssif;
    private javax.swing.JTextField TxtBorderPriceMod;
    private javax.swing.JTextField TxtBorderSif;
    private javax.swing.JTextField TxtFlavor1;
    private javax.swing.JTextField TxtFlavor2;
    private javax.swing.JTextField TxtFlavor3;
    private javax.swing.JTextField TxtFlavor4;
    private javax.swing.JTextField TxtFlavor5;
    private javax.swing.JTextField TxtQtflavorsMod;
    private javax.swing.JTextField TxtSizeMod;
    private javax.swing.JButton btnPratz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void ClearAll() {
        TxtFlavor1.setText("");
        TxtFlavor2.setText("");
        TxtFlavor3.setText("");
        TxtFlavor4.setText("");
        TxtFlavor5.setText("");
        Price = 0;
        CountFlavors = 0;
        LblPlus.setText("");
    }

    private void StartScreen() {
        PnSize.setVisible(true);
        PnSize.setPreferredSize(new Dimension(520,282));
        PnFlavors.setVisible(false);
        PnBorder.setVisible(false);
        TxtFlavor3.setVisible(false);
        TxtFlavor4.setVisible(false);
        TxtFlavor5.setVisible(false);
        LblFlavor3.setVisible(false);
        LblFlavor4.setVisible(false);
        LblFlavor5.setVisible(false);
        PnOrder.setVisible(false);
        PnBebidas.setVisible(false);
    }

    private void SelectFlavor(String Text) {       
        if (TxtFlavor1.getText().equals("")){
            TxtFlavor1.setText(Text);
            flavor.add(0, TxtFlavor1.getText());
        }else if (TxtFlavor2.getText().equals("")){
            TxtFlavor2.setText(Text);
            flavor.add(1, TxtFlavor2.getText());
        }else if ((TxtFlavor3.getText().equals("")) && (TxtFlavor3.isVisible())){
            TxtFlavor3.setText(Text);
            flavor.add(2, TxtFlavor3.getText());
        }else if ((TxtFlavor4.getText().equals("")) && (TxtFlavor4.isVisible())){
            TxtFlavor4.setText(Text);
            flavor.add(3, TxtFlavor4.getText());
        }else if ((TxtFlavor5.getText().equals("")) && (TxtFlavor5.isVisible())){
            TxtFlavor5.setText(Text);
            flavor.add(4, TxtFlavor5.getText());
        }
        Pizza1.setflavors(flavor);
    }

    private double SomaTotal(double PriceFlavor, double PriceBorder, Double price, Double price2) {
        double r;
        r = PriceFlavor + PriceBorder + price + price2;
        return r;
    }

    private double somabebidas(double c, double h, double w, double p) {
        double r;
        r = c + h + w + p;
        return r;
    }
}
